name: "csfb-topology"

config:
  topology.workers: 30
  project.spout.type: KAFKA_OLD_LOW_LEVEL
  project.spout.file.topics: ["lte_s1_mme", "lte_sgs", "mc_call", "mc_paging", "mc_location"]

  project.spout.ftp.reader.threads: 10
  project.spout.kafka.reader.threads: 128
  project.spout.redis.reader.threads: 10
#  the redis scan delay this time3600000
  project.spout.redis.buffer.ms: 10800000
  project.spout.parallelism: 10
  project.spout.zk.connect: "10.11.122.136:2181/eastcom_ue/csfb_partition_manager"
  project.spout.zk.kafka.connect: "10.11.122.136:2181,10.11.122.137:2181,10.11.122.138:2181,10.11.122.139:2181,10.11.122.140:2181,10.11.122.141:2181,10.11.122.142:2181/eastcom_ue"
  project.redis.partition.size: 100000
#  project.bolt.parallelism: 10
  project.bolt.kafka.writer.threads: 10

# MQ conf
  project.mq.broker.url: "tcp://10.221.247.50:61616"
  project.mq.queue.name: "Q_EVENT_PMCA_FILE2"

  topology.worker.childopts: "-server -Xms6g -Xmx6g -Xmn2g -XX:PermSize=96m -XX:MaxPermSize=96m -XX:+UseParallelGC -XX:+UseParallelOldGC -XX:ParallelGCThreads=4 -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -Xloggc:/tmp/gc-%ID%.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=1m"
  topology.fall.back.on.java.serialization: false
  topology.skip.missing.kryo.registrations: false
  topology.acker.executors: 0
  topology.executor.send.buffer.size: 2048
  topology.executor.receive.buffer.size: 2048
  topology.receiver.buffer.size: 64
  topology.transfer.buffer.size: 8192
  storm.messaging.netty.sync.mode: false
  topology.buffer.size.limited: false

  topology.backpressure.enable: true
  backpressure.disruptor.high.watermark: 0.9
  backpressure.disruptor.low.watermark:  0.4


  csvparser.selector.class: com.eastcom.csfb.storm.base.TopicCSVParsers

#  worker.childopts: "-Xmx3g"
  topology.metrics.consumer.register:
    - class: "org.apache.storm.metric.LoggingMetricsConsumer"
      parallelism.hint: 1

# kafka conf
  # common
  kafka.group.id: csfb_topology
  kafka.bootstrap.servers: "10.11.94.54:6667,10.11.94.62:6667,10.11.94.70:6667,10.11.94.77:6667,10.11.94.177:6667,10.11.94.179:6667,10.11.94.183:6667,10.11.94.185:6667,10.11.94.186:6667,10.11.94.190:6667,10.11.94.192:6667,10.11.94.107:6667,10.11.94.100:6667,10.11.94.92:6667,10.11.94.84:6667,10.11.94.156:6667"
  # reader
  kafka.topic.names: ["r_lte_s1_mme", "r_lte_sgs", "r_mc_call", "r_mc_paging", "r_mc_location"]
  kafka.key.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  kafka.value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  kafka.auto.offset.reset: latest
  # writer
  project.bolt.kafka.writer.topic: r_csfb
#  kafka.acks: 1
#  kafka.retries: 1
#  kafka.batch.size: 16384
#  kafka.linger.ms: 0
#  kafka.buffer.memory: 33554432
#  kafka.key.serializer: org.apache.kafka.common.serialization.StringSerializer
#  kafka.value.serializer: org.apache.kafka.common.serialization.StringSerializer

#includes:
#  - resource: false
#    file: "../flux/redisPool.yaml"
#    override: false


  jedis.pool.zookeeper.address: "10.11.122.136:2181,10.11.122.137:2181,10.11.122.138:2181,10.11.122.139:2181,10.11.122.140:2181,10.11.122.141:2181,10.11.122.142:2181"
  jedis.pool.zookeeper.timeout: 10000
  jedis.pool.cluster: cluster01
  jedis.pool.password: 'stream!23$'
  jedis.pool.maxtotal: 200

  pubsub.jedis.address: 10.11.94.160:6301
  pubsub.jedis.password: stream!23$

#  jedis.minIdle: 4
#  jedis.maxIdle: 4
#  jedis.maxTotal: 4
#  jedis.testOnBorrow: false
#  jedis.password: stream!23$
#  jedis.addresses:
#    - 10.11.94.155:6451
#    - 10.11.94.160:6451
#    - 10.11.94.161:6451
#    - 10.11.94.162:6451
#    - 10.11.94.163:6451
#    - 10.11.94.167:6451
#    - 10.11.94.168:6451
#    - 10.11.94.169:6451
#    - 10.11.94.170:6451
#    - 10.11.94.171:6451
#    - 10.11.94.175:6451
#    - 10.11.94.176:6451
#    - 10.11.94.204:6451
#    - 10.11.94.205:6451
#    - 10.11.94.206:6451
#    - 10.11.94.207:6451
#    - 10.11.94.208:6451
#    - 10.11.94.209:6451
#    - 10.11.94.210:6451
#    - 10.11.94.211:6451
#    - 10.11.94.212:6451
#    - 10.11.94.213:6451
#    - 10.11.94.155:6452
#    - 10.11.94.160:6452
#    - 10.11.94.161:6452
#    - 10.11.94.162:6452
#    - 10.11.94.163:6452
#    - 10.11.94.167:6452
#    - 10.11.94.168:6452
#    - 10.11.94.169:6452
#    - 10.11.94.170:6452
#    - 10.11.94.171:6452
#    - 10.11.94.175:6452
#    - 10.11.94.176:6452
#    - 10.11.94.204:6452
#    - 10.11.94.205:6452
#    - 10.11.94.206:6452
#    - 10.11.94.207:6452
#    - 10.11.94.208:6452
#    - 10.11.94.209:6452
#    - 10.11.94.210:6452
#    - 10.11.94.211:6452
#    - 10.11.94.212:6452
#    - 10.11.94.213:6452

#  - resource: false
#    file: "../flux/serializer.yaml"
#    override: false
  topology.kryo.register:
     - com.eastcom.csfb.data.ltesignal.LteS1Mme: com.eastcom.csfb.data.ltesignal.serializer.LteS1MmeSerializer
     - com.eastcom.csfb.data.ltesignal.LteSGs: com.eastcom.csfb.data.ltesignal.serializer.LteSgsSerializer
     - com.eastcom.csfb.data.mc.McCallEvent: com.eastcom.csfb.data.mc.serializer.McCallSerializer
     - com.eastcom.csfb.data.mc.McLocationUpdate: com.eastcom.csfb.data.mc.serializer.McLocationUpdateSerializer
     - com.eastcom.csfb.data.mc.McPaging: com.eastcom.csfb.data.mc.serializer.McPagingSerializer
     #- java.util.LinkedHashMap: com.eastcom.csfb.storm.base.common.LinkedHashMapSerializer
     - java.util.LinkedHashMap: com.esotericsoftware.kryo.serializers.MapSerializer

#  - resource: false
#    file: "../flux/hdfs-conf.yaml"
#    override: false
  hdfs.url: "hdfs://hdp"
  hdfs.path: "/rawdata/xdr/lte/lte_csfb/"
  hdfs.batch: 100000
  hdfs.createDir.interval: 5
  hdfs.file.content.split: |
  hdfs.file.name.prefix: csfb_


#topologySource:
#    className: "com.eastcom.csfb.storm.topo.CsfbTopology"
#    methodName: "getCsfbTopology"

# spout definitions
spouts:
  - id: "csfbSpout"
    className: "com.eastcom.csfb.storm.topo.CsfbSpout"
    parallelism: 10

# bolt definitions
bolts:
  - id: "extractSignalBolt"
    className: "com.eastcom.csfb.storm.topo.ExtractSignalBolt"
    parallelism: 10
  - id: "outputKafkaBolt"
    className: "com.eastcom.csfb.storm.topo.OutputKafkaBolt"
    parallelism: 10

#stream definitions
streams:
  - name: "csfbSpout --> extractSignalBolt"
    from: "csfbSpout"
    to: "extractSignalBolt"
    grouping:
      type: FIELDS
      args: ["partition"]

  - name: "extractSignalBolt --> outputKafkaBolt"
    from: "extractSignalBolt"
    to: "outputKafkaBolt"
    grouping:
      type: SHUFFLE
